apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    snappyflow/projectname: <yourprojectname> # insert your project name here
    snappyflow/appname: <yourapplicationname> # insert your app name here
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 5432
      targetPort: tcp
      protocol: TCP
      name: tcp
  selector:
    app: postgres
